
security:
  jwt:
    secret: ${JWT_SECRET:VGhpc0lzQVN1cGVyU2V5VGhhdFNob3VsZEJlMzJCeXRlc0xvbmc=}
    expirationMs: ${JWT_EXPIRATION_MS:3600000}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/applyin}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
